version: '3.5'

services:

  web:
    restart: always
    build: ./
#    image: sterneberg/foo
    ports:
      - 8080:8080
    networks:
      - front-tier
    command: './app'

networks:
  front-tier:
    driver: bridge
